stages:
  - test
  - coverage

.build:
  tags:
    - sandbox

test:
  extends: .build
  only:
    - merge_requests
  stage: test
  script:
    - make test

coverage:
  extends: .build
  only:
    - master
  stage: coverage
  script:
    - cd test && go get -t && go test -i
    - tfcoverage -d . --disableColor
